crossmint:
  api:
    candidate-id: [your-id]
    polyanet-url: https://challenge.crossmint.io/api/polyanets
    goal-url: https://challenge.crossmint.io/api/map/[your-id]/goal
    soloon-url: https://challenge.crossmint.io/api/soloons
    cometh-url: https://challenge.crossmint.io/api/comeths