crossmint:
  api:
    candidate-id:
    polyanet-url: https://challenge.crossmint.io/api/polyanets
    goal-url: https://challenge.crossmint.io/api/map/your-id/goal
  retry:
    max-attempts: 10
    delay: 4000

spring:
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    io.crossmint: DEBUG
